### ISSUE TITLE
[Bug]: Block indentation not working as expected

### ISSUE THREAD

**Issue by Telokis** [racz16/WebGL-GLSL-Editor#61] opened 2024-07-09 17:44 UTC
### The extension's version

v1.3.8

### VS Code's version

1.91

### Extension host

Desktop VS Code

### Operating system

Windows 10 x64

### Description

Inside blocks, nothing is indented, see below:

Before saving:
![image](https://github.com/racz16/WebGL-GLSL-Editor/assets/6382729/7ab13331-ff98-468b-90f9-228bb6a0ca23)

After saving:
![image](https://github.com/racz16/WebGL-GLSL-Editor/assets/6382729/9b33753d-8174-411d-9ca1-56dea3cd5ad0)

I just installed the extension for the first time ever. I also tried after disabling absolutely ALL of my extensions and only keeping yours enabled, same behavior.

**Comment by racz16** [comment] 2024-07-09 18:16
Thank you for reporting the problem. 

First of all, the extension can do 2 different things: indentation, and formatting. When you press `Enter`, the cursor is indented based on the surrounding code. So for example, if you're in a block, the cursor will be indented by a tab or something similar. Formatting adds and removes white spaces when you press `Alt` + `Shift` + `F`. So I assume your problem is with formatting because it happens when you save the document, but just to make sure, please format the code, and press `Enter` in different places, and tell me what happens in each case.

By default, the extension doesn't do anything when you save a document, but you might turned on `Editor: Format On Save` in the settings. 

I typed the code from your screenshot, with the same extension and VS Code version, but I couldn't reproduce the problem. Could you paste the whole source code, because maybe there is a preprocessor directive or something else that causes the problem in the earlier lines? Also, could you press right-click on the source code, and select, `Format Document With...`? It'll show you the default formatter which is used when you save the document.

At the moment these are my ideas, but it's really strange that I couldn't reproduce the problem. Especially since you said that you disabled all the other extensions.

**Comment by Telokis** [comment] 2024-07-09 21:48
The whole code I used was

```glsl
#[compute]
#version 450

// Invocations in the (x, y, z) dimension
layout(local_size_x = 2, local_size_y = 1, local_size_z = 1) in;

// A binding to the buffer we create in our script
layout(set = 0, binding = 0, std430) restrict buffer MyDataBuffer {
  float data[];
}
my_data_buffer;

// The code we want to execute in each invocation
void main() {
  // gl_GlobalInvocationID.x uniquely identifies this invocation across all work
  // groups
  my_data_buffer.data[gl_GlobalInvocationID.x] *= 2.0;
}
```

The `#[compute]` directive is meant for [Godot Compute Shaders](https://docs.godotengine.org/en/stable/tutorials/shaders/compute_shaders.html)

**Comment by racz16** [comment] 2024-07-09 22:44
Okay, now I can see the problem. This extension only supports GLSL ES 100, and GLSL ES 300, because these versions are available in WebGL. Also, `#[compute]` is not part of any GLSL versions, it's Godot's own syntax. 

Funnily enough, the problem is not the `#[compute]`, but `restrict`, and `buffer`. These are not known keywords in GLSL ES 100, and GLSL ES 300. The extension can parse the code if it's not entirely valid, for example, `local_size_x` is not a valid layout qualifier in these language versions, but they are similar to other layout qualifiers, so the extension can deal with those. However, this code snippet is different enough, that the extension can't handle it:
```
layout(set = 0, binding = 0, std430) restrict buffer MyDataBuffer {
  float data[];
}
my_data_buffer;
```
This doesn't only break formatting, but almost all features of the extension. You can try it out by adding some code before and after these lines. Before it, the outline, go to definition, hover, highlights, and a lot of other features are working, but after it, they don't work, or work in a very limited way.

So, the bad news is that I won't fix this, because this extension only supports shader languages available in WebGL. The good news is that I'm working on a new extension that will support all 17 versions of GLSL. If everything goes according to the plans I'll release it in the next week. It'll contain syntax highlights, diagnostics, and a bunch of smaller features. But over time it'll make this extension deprecated.

**Comment by Telokis** [comment] 2024-07-10 01:37
Oh ok, thank you very much for clarifying the situation, I had no real knowledge of the GLSL versions being supported by WebGL and since you extension was pretty high when sorted by downloads, I took it without thinking too much about it!  
In the meantime I've moved to clang-format even if it's quite basic!

Thank you for the time you took to reply! I'll let you decide whether to close this issue or not!

**Closed** 2024-07-10 01:49 UTC
Labels: bug
